pipeline {

    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
                sh 'cp target/*.jar deploy/app.jar'
                sh 'cd deploy && docker build -t sagaranin/wiki-sse-listener:${BUILD_NUMBER} .'
            }
        }
        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_sagaranin', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'docker login -u $USERNAME -p $PASSWORD'
                }
            }
        }
        stage('Docker Push') {
            steps {
                sh 'docker push sagaranin/wiki-sse-listener:${BUILD_NUMBER}'
            }
        }
        stage('Deploy') {
            steps {
                sh "cd deploy && sed -i 's/BUILD_NUMBER/${BUILD_NUMBER}/g' wiki-sse-listener-deployment.yaml"
                sh 'cd deploy && kubectl apply -f wiki-sse-listener-deployment.yaml'
            }
        }
    }
}
