pipeline {

    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
                sh 'cp target/*.jar deploy/app.jar'
                sh 'cd deploy && docker build -t sagaranin/wiki-sse-listener:latest .'
            }
        }
        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_sagaranin', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'docker login -u $USERNAME -p $PASSWORD'
                }
            }
        }
        stage('Docker Push') {
            steps {
                sh 'docker push sagaranin/wiki-sse-listener:latest'
            }
        }
        stage('Deploy') {
            steps {
                sh 'scp deploy/wiki-sse-listener-deployment.yaml root@master:/deployments'
                sh 'ssh root@master kubectl replace -f /deployments/wiki-sse-listener-deployment.yaml'
            }
        }
    }
}
