pipeline {

    stages {

        stage('Docker Build') {
            steps {
                sh 'mvn clean install'
                sh 'cd deploy && docker build -t sagaranin/wiki-sse-listener:latest -t sagaranin/wiki-sse-listener:${BUILD_NUMBER} .'
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_sagaranin', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                }
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push sagaranin/wiki-sse-listener:latest; docker push sagaranin/wiki-sse-listener:${BUILD_NUMBER}'
            }
        }

    }
}
